# Generated by Django 4.2.13 on 2026-05-20 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("water_monitor", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WaterLevelReading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("water_level", models.FloatField(help_text="Water level in cm")),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "device_id",
                    models.CharField(
                        default="ESP8266_01",
                        help_text="Device identifier",
                        max_length=50,
                    ),
                ),
                (
                    "battery_level",
                    models.FloatField(
                        blank=True, help_text="Battery percentage (0-100)", null=True
                    ),
                ),
                (
                    "signal_strength",
                    models.IntegerField(
                        blank=True, help_text="WiFi RSSI signal strength", null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Water Level Reading",
                "verbose_name_plural": "Water Level Readings",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["-timestamp"], name="water_monit_timesta_eb3af8_idx"
                    ),
                    models.Index(
                        fields=["device_id"], name="water_monit_device__c0b53e_idx"
                    ),
                    models.Index(
                        fields=["water_level"], name="water_monit_water_l_fc61b6_idx"
                    ),
                ],
            },
        ),
    ]
